name: CI

env: {NODE_VERSION: 18}

on:
  push: {branches: [main, 'feature.*']}
  pull_request:

jobs:
  trunk_check:
    name: check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: trunk-io/trunk-action@sam/auto-setup
